### ISSUE TITLE
Объединить if

### ISSUE THREAD

**Issue by VladHolo628** [semastep96/Calc#1]
if (typeof a != 'number') { return 'Error' }
if (typeof b != 'number') { return 'Error' }

Можно 
if (typeof a != 'number' || typeof b != 'number') { return 'Error' }

И вместо отдельного if сделать else if
  **_else if_** (action == 'sum') { return sum(a, b) }

  else if (action == 'minus') { return minus(a, b) }
  else if (action == 'multiply') {return multiply(a, b)}
  else if (action == 'division') {return division(a, b)}
  else if (action == 'remainder') {return remainder(a, b)}
  else if (action == 'exponentiation') {return exponentiation(a, b)}
  return 'unknown operator';
}

**Comment by semastep96** [comment]
Отличная идея, спасибо!) Пошел делать)

**Comment by semastep96** [comment]
Готово
